name: 'tautulli'

networks:
  caddy:
    external: true
  media:
    external: true

services:
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    env_file: .env
    networks:
      - caddy
      - media
    # ports:
    #   - 8181:8181/tcp
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/tautulli/config:/config:rw
      - /mnt/docker/plex:/plex:ro
