
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/16 # caddy

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
# template: !include templates.yaml
