name: 'plex'

networks:
  media:
    external: true

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    env_file: .env
    networks:
      - media
    restart: unless-stopped
    ports:
      - 32400:32400/tcp # access to the Plex Media Server [required]
      - 1900:1900/udp   # access to the Plex DLNA Server
      - 32469:32469/tcp # access to the Plex DLNA Server
      - 5353:5353/udp   # older Bonjour/Avahi network discovery
      - 8324:8324/tcp   # controlling Plex for Roku via Plex Companion
      - 32410:32410/udp # current GDM network discovery
      - 32412:32412/udp # current GDM network discovery
      - 32413:32413/udp # current GDM network discovery
      - 32414:32414/udp # current GDM network discovery
    tmpfs:
      - /transcode
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/plex/config:/config:rw
      - /mnt/pool2/movies:/movies:ro
      - /mnt/pool2/series:/series:ro
      - /mnt/pool2/music:/music:ro
