name: 'portainer'

networks:
  caddy:
    external: true
  monitor:
    external: true

services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    env_file: .env
    networks:
      - caddy
      - monitor
    # ports:
    #   - 9000:9000/tcp
    #   - 9443:9443/tcp
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/portainer/data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
