name: 'influxdb'

networks:
  caddy:
    external: true
  monitor:
    external: true

services:
  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    env_file: .env
    networks:
      - caddy
      - monitor
    ports:
      - 8086:8086/tcp
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/influxdb/etc:/etc/influxdb2:rw
      - /mnt/docker/influxdb/var:/var/lib/influxdb2:rw
